CREATE DATABASE IF NOT EXISTS roleplaydb DEFAULT CHARACTER SET = "UTF8";

CONNECT roleplaydb;

CREATE TABLE IF NOT EXISTS SOLOROLEPLAY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  STATUS VARCHAR(20) NOT NULL,
  OWNER VARCHAR(255) NOT NULL,
  SOLOTEXT MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  CREATIONDATE DATETIME, 
  LASTUPDATE DATETIME
);

-- ALTER TABLE SOLOROLEPLAY CHANGE SOLOTEXT SOLOTEXT MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;

-- ALTER TABLE SOLOROLEPLAY MODIFY OWNER VARCHAR(255) NOT NULL;

CREATE TABLE IF NOT EXISTS USERPERSIST (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERID VARCHAR(255) NOT NULL UNIQUE,
  ROLE VARCHAR(32),
  DATA TEXT NOT NULL,
  CREATIONDATE DATETIME,
  PERSISTTIME DATETIME NOT NULL
);

-- ALTER TABLE USERPERSIST ADD ROLE VARCHAR(32);
-- ALTER TABLE USERPERSIST ADD CREATIONDATE DATETIME;

CREATE USER roleplaydbusr IDENTIFIED BY 'geheim';

GRANT ALL ON roleplaydb.* TO roleplaydbusr@'%';


